module.exports = ["Go Ahead, make my day", "I'll be back", "I am the Danger", "My name is Jeff", "I'm Batman", "You can't handle the truth",
    "It's a Trap", "Life's an ocean, sail it", "Life is too short to wait", "Quiet people have the loudest minds",
    "We will remember", "E.T. phone home", "	Bond, James Bond", "There's no place like home", "Elementary, my dear Watson",
    "Here's Johnny", "Hasta la vista, baby", "My precious", "No Luke, I am your Father", "A Dragon is not a slave", "Say hello to my little friend", "To Infinity and beyond",
    "May the Force be with you", "Everything you can imagine is real", "If not us, Who? If not Now, When?",
    "What goes around comes around", "Be Yourself, everyone else is already taken",
    "Whatever you are, be a good one", "It doesn't get easier, you just get better",
    "Be happy, be bright, be you", "Houston, we have a problem", "I'm king of the world", "I'm not insane, my mother had me tested", "Not all those who wander are lost",
    "What do we say to the God of Death", "Do or do not, there is no try",
    "The secret of getting ahead is getting started",
    "You can't win unless you learn how to lose", "Life is the sum of all your choices", "I love the smell of napalm in the morning",
    "Keep your friends close, but your enemies closer", "I feel the need - the need for speed", "I'm just gonna stay angry. I find that relaxes me", "Freedom means making your own choices",
    "With great power, comes great responsibility", "I don't want to survive. I want to live",
    "Pride is the fuel of human accomplishment",
    "Never make permanent decisions on Temporary feelings",
    "I'm going to make him an offer he can't refuse", "Get your stinking paws off me, you damned dirty ape.", "Be who you are and say what you feel because those who mind don't matter and those who matter don't mind",
    "Once you've accepted your flaws, no one can use them against you",
    "The man who passes the sentence should swing the sword",
    "A person who never made a mistake never tried anything new",
    "Don't let other people's complimnets get to your head and don't let their criticism get your heart",
    "Mama always said life was like a box of chocolates. You never know what you're gonna get "
];